### ISSUE TITLE
Building the new Treep

### ISSUE THREAD

**Issue by eblanca** [fsinapsi/TreeP#2]
Hello, glad to see this compiler is now up-to-date.
I'm going to build this in order to compile avinaptic on my linux distribution - it is debian based.
Now, as I only need to build avinaptic-cli, how can I skip iup dependency when building treep ?

**Comment by fsinapsi** [comment]
> I'm going to build this in order to compile avinaptic on my linux distribution - it is debian based.
> Now, as I only need to build avinaptic-cli, how can I skip iup dependency when building treep ?

Hi.
You can comment (or delete) the following line in the Makefile:
( cd trpiup && make TARGET=$(TARGET) CC=$(CC) AR=$(AR) )

avinaptic2-cli requires the following libraries

$ ldd `which avinaptic2-cli` | grep trp
	libtrpaud.so => /usr/local/lib/libtrpaud.so (0x00007fae54426000)
	libtrpvid.so => /usr/local/lib/libtrpvid.so (0x00007fae54411000)
	libtrpavi.so => /usr/local/lib/libtrpavi.so (0x00007fae54404000)
	libtrpid3tag.so => /usr/local/lib/libtrpid3tag.so (0x00007fae543ff000)
	libtrpmagic.so => /usr/local/lib/libtrpmagic.so (0x00007fae543de000)
	libtrpexif.so => /usr/local/lib/libtrpexif.so (0x00007fae543ad000)
	libtrppix.so => /usr/local/lib/libtrppix.so (0x00007fae5433d000)
	libtrpsqlite3.so => /usr/local/lib/libtrpsqlite3.so (0x00007fae54241000)
	libtrplept.so => /usr/local/lib/libtrplept.so (0x00007fae540fe000)
	libtrp.so => /usr/local/lib/libtrp.so (0x00007fae53e05000)
